version: "3.7"
services:
  mysql-standalone1:
    image: mysql:5.7
    network_mode: "host"
    container_name: mysql-standalone1
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: test              # name of database
      MYSQL_USER: testuser                # sample is the name of user
      MYSQL_PASSWORD: testuser@123          # password for sample user
      MYSQL_ROOT_PASSWORD: testuser@123    # password for root user
    #ports:
     # - 3306:3306                      # host port 3306 is mapper to docker port 3306
    expose:
      - 3306
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db:
#networks:
  #microservices-net:
    #driver: bridge
